### ISSUE TITLE
Update for Guzzle 7

### ISSUE THREAD

**Issue by ls5302** [ssi-anik/loguzz#2]
Hi,

Your code looks to work with Guzzle 7, but composer complains - I think it just needs a tweak in the composer.json:

        "guzzlehttp/guzzle": ">=6.2",

Thanks,

Lukasz

**Comment by ssi-anik** [comment]
can you please use the pipe for the composer package requirement and check if it passes the tests? if everything is okay, will you then please send a PR?

**Comment by ls5302** [comment]
I should have time to have a go other the next couple of days.

**Comment by ssi-anik** [comment]
It's okay. I have started working as well as fixing some issues

**Comment by ssi-anik** [comment]
Just released update for guzzle ^7.x with tag `v2.0`.
Thanks.

**Comment by ssi-anik** [comment]
Please submit a PR if there is anything wrong.

**Comment by ls5302** [comment]
I think, the reason the response is empty is because `body` doesn't get rewound in AbstractResponseFormatter::getResponseBody().

I note from version 1.2 the previous position was remember and then reset after the read using `$body->seek($previousPosition);`.
