### ISSUE TITLE
Class 'GuzzleHttp\Promise\Create' not found

### ISSUE THREAD

**Issue by srdmnc** [ssi-anik/loguzz#7]
Here's the exception we received in the production server.

> {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'GuzzleHttp\\Promise\\Create' not found at /prodPath/vendor/anik/loguzz/src/Middleware/LogMiddleware.php:191)

Additional screenshot:
![image](https://user-images.githubusercontent.com/41004879/178217526-7b6ecde6-8da8-4b47-af0d-23d9ed0880a9.png)

Any idea on how to resolve this?

**Comment by ssi-anik** [comment]
Can you specify the exact versions please?
